# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# Note - This can be run using something like pyuic5 main_window.ui > test.py

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window_(object):
    def setupUi(self, main_window_):
        main_window_.setObjectName("main_window_")
        main_window_.resize(177, 221)
        self.central_widget_ = QtWidgets.QWidget(main_window_)
        self.central_widget_.setObjectName("central_widget_")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.central_widget_)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 171, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vertical_layout_ = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vertical_layout_.setContentsMargins(4, 4, 4, 4)
        self.vertical_layout_.setObjectName("vertical_layout_")
        self.start_preview_btn_ = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.start_preview_btn_.setObjectName("start_preview_btn_")
        self.start_preview_btn_.clicked.connect(self.button_clicked)

        self.vertical_layout_.addWidget(self.start_preview_btn_)
        self.end_preview_btn_ = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.end_preview_btn_.setObjectName("end_preview_btn_")
        self.vertical_layout_.addWidget(self.end_preview_btn_)
        self.take_picture_btn_ = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.take_picture_btn_.setObjectName("take_picture_btn_")
        self.vertical_layout_.addWidget(self.take_picture_btn_)
        self.file_name_input_ = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.file_name_input_.setObjectName("file_name_input_")
        self.vertical_layout_.addWidget(self.file_name_input_)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vertical_layout_.addItem(spacerItem)
        main_window_.setCentralWidget(self.central_widget_)
        self.menubar = QtWidgets.QMenuBar(main_window_)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 177, 22))
        self.menubar.setObjectName("menubar")
        self.menutest = QtWidgets.QMenu(self.menubar)
        self.menutest.setObjectName("menutest")
        main_window_.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window_)
        self.statusbar.setObjectName("statusbar")
        main_window_.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menutest.menuAction())

        self.retranslateUi(main_window_)
        QtCore.QMetaObject.connectSlotsByName(main_window_)

    def retranslateUi(self, main_window_):
        _translate = QtCore.QCoreApplication.translate
        main_window_.setWindowTitle(_translate("main_window_", "MainWindow"))
        self.start_preview_btn_.setText(_translate("main_window_", "Start Preview"))
        self.end_preview_btn_.setText(_translate("main_window_", "End Preview"))
        self.take_picture_btn_.setText(_translate("main_window_", "Take Picture"))
        self.menutest.setTitle(_translate("main_window_", "Options"))

    def button_clicked(self):
        print("Button clicked")



def init():
    print("init")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window_ = QtWidgets.QMainWindow()
    ui = Ui_main_window_()
    ui.setupUi(main_window_)
    main_window_.show()

    init()

    sys.exit(app.exec_())

