# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_window_(object):
    def setupUi(self, main_window_):
        main_window_.setObjectName("main_window_")
        main_window_.resize(683, 567)
        self.central_widget_ = QtWidgets.QWidget(main_window_)
        self.central_widget_.setObjectName("central_widget_")
        self.layoutWidget = QtWidgets.QWidget(self.central_widget_)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 1, 168, 469))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 20, 167, 67))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.start_timelapse_btn_ = QtWidgets.QPushButton(self.layoutWidget1)
        self.start_timelapse_btn_.setObjectName("start_timelapse_btn_")
        self.horizontalLayout_2.addWidget(self.start_timelapse_btn_)
        self.stop_timelapse_btn_ = QtWidgets.QPushButton(self.layoutWidget1)
        self.stop_timelapse_btn_.setObjectName("stop_timelapse_btn_")
        self.horizontalLayout_2.addWidget(self.stop_timelapse_btn_)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.timelapse_delay_spinbox_ = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.timelapse_delay_spinbox_.setObjectName("timelapse_delay_spinbox_")
        self.horizontalLayout.addWidget(self.timelapse_delay_spinbox_)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.vertical_layout_ = QtWidgets.QVBoxLayout()
        self.vertical_layout_.setContentsMargins(4, 4, 4, 4)
        self.vertical_layout_.setObjectName("vertical_layout_")
        self.status_ = QtWidgets.QLabel(self.layoutWidget)
        self.status_.setObjectName("status_")
        self.vertical_layout_.addWidget(self.status_)
        self.opencv_capture_ = QtWidgets.QPushButton(self.layoutWidget)
        self.opencv_capture_.setObjectName("opencv_capture_")
        self.vertical_layout_.addWidget(self.opencv_capture_)
        self.start_preview_btn_ = QtWidgets.QPushButton(self.layoutWidget)
        self.start_preview_btn_.setObjectName("start_preview_btn_")
        self.vertical_layout_.addWidget(self.start_preview_btn_)
        self.end_preview_btn_ = QtWidgets.QPushButton(self.layoutWidget)
        self.end_preview_btn_.setObjectName("end_preview_btn_")
        self.vertical_layout_.addWidget(self.end_preview_btn_)
        self.take_picture_btn_ = QtWidgets.QPushButton(self.layoutWidget)
        self.take_picture_btn_.setObjectName("take_picture_btn_")
        self.vertical_layout_.addWidget(self.take_picture_btn_)
        self.start_video_recording_btn_ = QtWidgets.QPushButton(self.layoutWidget)
        self.start_video_recording_btn_.setObjectName("start_video_recording_btn_")
        self.vertical_layout_.addWidget(self.start_video_recording_btn_)
        self.stop_video_recording_btn_ = QtWidgets.QPushButton(self.layoutWidget)
        self.stop_video_recording_btn_.setObjectName("stop_video_recording_btn_")
        self.vertical_layout_.addWidget(self.stop_video_recording_btn_)
        self.save_last_20_seconds_btn_ = QtWidgets.QPushButton(self.layoutWidget)
        self.save_last_20_seconds_btn_.setObjectName("save_last_20_seconds_btn_")
        self.vertical_layout_.addWidget(self.save_last_20_seconds_btn_)
        self.file_name_input_ = QtWidgets.QLineEdit(self.layoutWidget)
        self.file_name_input_.setObjectName("file_name_input_")
        self.vertical_layout_.addWidget(self.file_name_input_)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vertical_layout_.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.vertical_layout_)
        self.image_label_ = QtWidgets.QLabel(self.central_widget_)
        self.image_label_.setGeometry(QtCore.QRect(180, 0, 251, 231))
        self.image_label_.setObjectName("image_label_")
        main_window_.setCentralWidget(self.central_widget_)
        self.menubar = QtWidgets.QMenuBar(main_window_)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 683, 24))
        self.menubar.setObjectName("menubar")
        self.menutest = QtWidgets.QMenu(self.menubar)
        self.menutest.setObjectName("menutest")
        main_window_.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window_)
        self.statusbar.setObjectName("statusbar")
        main_window_.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menutest.menuAction())

        self.retranslateUi(main_window_)
        QtCore.QMetaObject.connectSlotsByName(main_window_)

    def retranslateUi(self, main_window_):
        _translate = QtCore.QCoreApplication.translate
        main_window_.setWindowTitle(_translate("main_window_", "MainWindow"))
        self.groupBox.setTitle(_translate("main_window_", "Timelapse"))
        self.start_timelapse_btn_.setText(_translate("main_window_", "Start"))
        self.stop_timelapse_btn_.setText(_translate("main_window_", "Stop"))
        self.label.setText(_translate("main_window_", "Delay (Seconds)"))
        self.status_.setText(_translate("main_window_", "TextLabel"))
        self.opencv_capture_.setText(_translate("main_window_", "OpenCV Capture"))
        self.start_preview_btn_.setText(_translate("main_window_", "Start Preview"))
        self.end_preview_btn_.setText(_translate("main_window_", "End Preview"))
        self.take_picture_btn_.setText(_translate("main_window_", "Take Picture"))
        self.start_video_recording_btn_.setText(_translate("main_window_", "Start Video"))
        self.stop_video_recording_btn_.setText(_translate("main_window_", "Stop Video"))
        self.save_last_20_seconds_btn_.setText(_translate("main_window_", "Save last 20 seconds"))
        self.image_label_.setText(_translate("main_window_", "ImageLabel"))
        self.menutest.setTitle(_translate("main_window_", "Options"))

